### PR TITLE
Update teamspeak3_viewer_class.php

### PR DESCRIPTION
**Pull request by yesszus**
Add lang codes and pharses.

### CODE REVIEW

**Comment by yesszus** [comment]
Done.

**Comment by Moc** [comment]
Thank you for your work @yesszus, I have some comments:

- Please note that many of the plugins on my github account are still in development. The teamspeak plugin is an example of a plugin which has not yet been released. As these plugins are still in development, I may still change the code and a lot of LAN's as well. It is therefore a waste of time to already translate now. 

- Please do not make modifications to non-LAN code such as changing the default values in plugin.xml (ts3_flags option and the sitelinks). The plugin is still in development and I have the code written with some goals in mind. 

- I will merge your changes in, but before releasing the first stable version, the LANs will need to be rechecked. 

Don't take this the wrong way, I really appreciate your work. I just want to avoid you wasting your time on plugins that are still in development 😄

**Comment by yesszus** [comment]
Ok!

**Comment by Moc** [comment]
I'll still merge it in :smile See my last comment.

**Pull request merged**
